---
- name: Check SSH and install NTP
  hosts: localhost
  become: true

  tasks:
    - name: Check SSH service status
      service:
        name: ssh
        state: started
      register: ssh_service_status

    - name: Print SSH service status
      debug:
        msg: "SSH service is {{ ssh_service_status.state }}"

    - name: Remove conflicting packages
      apt:
        name:
          - ntpsec
          - systemd-timesyncd
        state: absent
      ignore_errors: yes

    - name: Install NTP package
      apt:
        name: ntp
        state: present
      ignore_errors: yes

    - name: Ensure NTP service is running
      service:
        name: ntp
        state: started
        enabled: true
      ignore_errors: yes

    - name: Print NTP service status
      command: systemctl status ntp --no-pager
      register: ntp_status
      changed_when: false
      ignore_errors: yes

    - name: Show NTP service status
      debug:
        msg: "{{ ntp_status.stdout }}"
